"""migrate by docker command

Revision ID: 3ab8906cd599
Revises: 5639e4cdfdd6
Create Date: 2018-05-31 02:43:24.348908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab8906cd599'
down_revision = '5639e4cdfdd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
